# Generated by Django 4.1.4 on 2022-12-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0002_abs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abs',
            name='title',
            field=models.TextField(),
        ),
    ]
