# Generated by Django 4.1.4 on 2022-12-12 13:49

from django.db import migrations


#
def load_initial_data(apps, schema_editor):
    categori = apps.get_model('authUser', 'CategoriUser')
    str_list = "Танки,Хилы,ДД,Торговцы,Гилдмастеры,Квестгиверы,Кузнецы,Кожевники,Зельевары,Мастера заклинаний".split(',')
    for item in str_list:
        categori.objects.create (
            name = item 
        )
   


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
