# Generated by Django 4.1.4 on 2022-12-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0003_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.PositiveIntegerField(),
        ),
    ]
